version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    image: postgres:9.5

