# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9461ef9860ec6c679db9acbb69a5d4e06699bb20be0704549fbd6faaad8a36410a0aa9e85a8391d6478a80e17595d945a6a94d25ef7b4f611b36a37e515ab269

test:
  secret_key_base: 1e3ad7c59b0e52989edd96f8b21670463198c4ac8fe9d06b3f2f1ade2eea69c0677067c47c64de8a9ea55f0a503375c73cf51be69eae299da7bd31cf41eb44a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
